export const softwareRelease = {
  version: "1.9.0",
  title: "Haber merkezi ve okur modülleri",
  date: "2026-09-17",
  items: [
    "Manşetlerde Türkiye saatine göre yayın aralığı, sürükle-bırak/klavye sıralaması ve mobil önizleme.",
    "Konu dosyaları: özet, kişi/kurumlar, ilişkili haberler ve taslak/yayın akışı.",
    "Yerel merkez: şehir/ilçe dosyaları ve konum izni istemeyen şehir araması.",
    "Canlı anlatım: saatli gelişmeler, sabitleme, düzeltme notları ve paylaşım bağlantıları.",
    "Yazar biyografisi, uzmanlık yönetimi ve cihazda yazar/konu takibi.",
    "İhbar ve düzeltme formu, başvuru numarası, moderasyon kuyruğu ve hız sınırı.",
    "E-posta bülteni: çift aşamalı onay, çıkış, günlük özet hazırlama ve editör onaylı küçük gönderim grupları. Sağlayıcı ayarı gerekir.",
    "Medya odak noktası, kaynak/tarih kalite uyarıları ve cron sağlık kaydı.",
    "AI çıktıları editör incelemesine alınır; doğrudan otomatik yayın kaldırıldı, editör önerilerine kullanım sınırı eklendi.",
    "Ana sayfa keşif alanı ve Avcı E-Ticaret için siyah/kırmızı, mobil uyumlu marka bannerları.",
  ],
};
export const newsroomModules = [
  { title: "Yayın kalite kontrolü", href: "/admin/haberler", detail: "Başlık, spot, görsel, kaynak ve tarih uyarıları" },
  { title: "Manşet planlayıcı", href: "/admin/vitrin", detail: "Yayın aralığı, sıralama, önizleme ve otomatik alternatif" },
  { title: "Medya merkezi", href: "/admin/medya", detail: "Arama, kaynak/hak notları, odak noktası" },
  { title: "Operasyon merkezi", href: "/admin/operasyon", detail: "Kaynak işleri, cron sağlığı ve yapılandırma durumu" },
  { title: "Konu dosyaları", href: "/admin/dosyalar", detail: "Özet, ilgili haberler, kişi ve kurumlar" },
  { title: "Yazar profilleri", href: "/admin/yazarlar", detail: "Biyografi, uzmanlık ve haber listesi" },
  { title: "Canlı anlatım", href: "/admin/dosyalar", detail: "Saatli gelişmeler, sabitleme, düzeltme ve bağlantı" },
  { title: "Yerel haber merkezi", href: "/admin/dosyalar", detail: "Şehir ve ilçe dosyaları" },
  { title: "Kaydedilenler ve takip", href: "/takip", detail: "Cihazda okuma listesi ve konu/yazar takibi" },
  { title: "İhbar ve düzeltme", href: "/admin/basvurular", detail: "Başvuru numarası, moderasyon ve iç notlar" },
  { title: "E-posta bülteni", href: "/admin/bulten", detail: "Sağlayıcı bağlantısından sonra doğrulanmış abonelik ve gönderim" },
  { title: "AI editör yardımcısı", href: "/admin/haberler", detail: "Yapılandırılmış sağlayıcıyla editör onaylı öneriler" },
];
