"use client";
import { useState } from "react";
import Image from "next/image";
import type { HomeSettings } from "@/server/services/homeSettingsService";
import { formatPublicationSchedule } from "@/lib/utils/publicationSchedule";
type Option = { id: string; title: string; coverMedia: { url: string } | null };
export function HeadlinePlanner({ settings, articles }: { settings: HomeSettings; articles: Option[] }) {
  const [slots, setSlots] = useState([0, 1, 2].map(i => ({ id: settings.headlineIds[i] ?? "", start: settings.windows?.[i]?.startAt ? formatPublicationSchedule(new Date(settings.windows[i]!.startAt!)) : "", end: settings.windows?.[i]?.endAt ? formatPublicationSchedule(new Date(settings.windows[i]!.endAt!)) : "" })));
  const [dragging, setDragging] = useState<number | null>(null);
  function move(from: number, to: number) { if (from < 0 || to < 0 || from > 2 || to > 2) return; setSlots(old => { const next = [...old]; [next[from], next[to]] = [next[to]!, next[from]!]; return next; }); }
  function set(index: number, field: "id" | "start" | "end", value: string) { setSlots(old => old.map((slot, i) => i === index ? { ...slot, [field]: value } : slot)); }
  return <div className="space-y-4"><p className="text-caption">Manşetleri sürükleyerek veya yukarı/aşağı düğmeleriyle sıralayın. Tarihler Türkiye saatidir; süresi dışında otomatik haber seçilir.</p>
    {slots.map((slot, i) => <section key={i} className="rounded-xl border border-line-dark p-4" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); if (dragging !== null) move(dragging, i); setDragging(null); }}><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><strong>{i + 1}. manşet</strong><div className="flex gap-3"><button type="button" draggable onDragStart={() => setDragging(i)} onDragEnd={() => setDragging(null)} aria-label={`${i + 1}. manşeti sürükle`}>↕</button><button type="button" disabled={i === 0} onClick={() => move(i, i - 1)} className="disabled:opacity-30" aria-label={`${i + 1}. manşeti yukarı taşı`}>Yukarı</button><button type="button" disabled={i === 2} onClick={() => move(i, i + 1)} className="disabled:opacity-30" aria-label={`${i + 1}. manşeti aşağı taşı`}>Aşağı</button></div></div>
      <label className="block text-caption">Haber<select name={["primary", "secondary1", "secondary2"][i]} value={slot.id} onChange={e => set(i, "id", e.target.value)} className="mt-2 block w-full rounded border border-line-dark bg-surface-dark p-3"><option value="">Otomatik seçim</option>{articles.map(a => <option key={a.id} value={a.id}>{a.title}</option>)}</select></label>
      <div className="mt-3 grid gap-3 sm:grid-cols-2">{(["start", "end"] as const).map(field => <label key={field} className="text-caption">{field === "start" ? "Başlangıç" : "Bitiş"}<input type="datetime-local" name={`${field}${i}`} value={slot[field]} onChange={e => set(i, field, e.target.value)} className="mt-1 block w-full border border-line-dark bg-transparent p-2" /></label>)}</div></section>)}
    <details className="rounded-xl border border-line-dark p-4"><summary className="cursor-pointer">Mobil manşet sırası önizlemesi</summary><div className="mx-auto mt-4 max-w-[390px] space-y-3">{slots.map((slot, i) => { const a = articles.find(item => item.id === slot.id); return <div key={i} className="overflow-hidden rounded-lg border border-line-dark">{a?.coverMedia && <Image src={a.coverMedia.url} alt="" width={390} height={180} unoptimized className="h-36 w-full object-cover" />}<p className="p-4 font-serif">{i + 1}. {a?.title ?? "Otomatik haber seçimi"}</p></div>; })}</div><p className="mt-3 text-caption">Yerleşim önizlemesi; zaman aralığı dışında otomatik haber gösterilir.</p></details>
  </div>;
}
