import Link from "next/link";
import { ActionForm } from "@/components/admin/ActionForm";
import { submitReaderReport } from "@/server/actions/readerSubmissionActions";
export const metadata = { title: "İhbar ve düzeltme merkezi" };
export default async function ReaderReport({ searchParams }: { searchParams: Promise<{ haber?: string }> }) {
  const q = await searchParams;
  return <div className="container-page py-10"><header className="module-heading"><p className="eyebrow">OKURDAN HABER MERKEZİNE</p><h1>Bir haber paylaşın.<br />Bir yanlışı düzeltelim.</h1><p>İhbar ve düzeltme talepleri yayımlanmadan önce editörler tarafından incelenir. Acil durumlar için ilgili acil yardım kanallarını kullanın.</p></header>
    <ActionForm action={submitReaderReport}><label>Başvuru türü<select name="kind" defaultValue={q.haber ? "CORRECTION" : "TIP"}><option value="TIP">Haber ihbarı</option><option value="CORRECTION">Düzeltme talebi</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label>Ad soyad<input name="name" required minLength={2} maxLength={100} autoComplete="name" /></label><label>E-posta<input name="email" type="email" required maxLength={254} autoComplete="email" /></label></div><label>Konu<input name="title" required minLength={5} maxLength={180} /></label><label>İlgili haber adresi<input name="articleUrl" type="url" defaultValue={q.haber?.slice(0, 2000)} maxLength={2000} /></label><label>Açıklama<textarea name="message" required minLength={20} maxLength={5000} rows={7} /></label><label className="hidden" aria-hidden>Web sitesi<input name="website" tabIndex={-1} autoComplete="off" /></label><p className="text-caption">Bu form dosya kabul etmez. İlgili kaynağın bağlantısını ve doğrulanabilir ayrıntıları açıklamaya ekleyebilirsiniz. Hassas kişisel bilgi paylaşmayın.</p><label className="flex gap-2"><input name="consent" type="checkbox" required /><span><Link href="/gizlilik" className="underline">Gizlilik açıklamasını</Link> okudum; bilgilerimin bu başvuruyu değerlendirmek ve benimle iletişim kurmak için kullanılmasını kabul ediyorum.</span></label><button className="module-button">Editöre ilet</button></ActionForm></div>;
}
